### ISSUE TITLE
help required to automate fmask on mac

### ISSUE THREAD

**Issue by palaiya** [GERSL/Fmask4#11]
Hi,
I have download the 4.0 version of fmask and i was able to mask the clouds etc using the GUI. I wanted to understand how do i automate using command line. I have gone through the tutorials which was written for 3.3. version and for windows. But didn't understand.
Moreover, I have one more question what does " Number of dilated pixels for XYZ" means ? Does it mean you take 3*3 matrix and replace the whole 3*3 matrix with one value?

**Comment by prs021** [comment]
Hi Shi,

Can you help here?
Thanks!

Zhe

ZHE ZHU
ASSISTANT PROFESSOR OF REMOTE SENSING
NATURAL RESOURCES AND THE ENVIRONMENT
UNIVERSITY OF CONNECTICUT 
OFFICE: 860.486.6885 | EMAIL: ZHE@UCONN.EDU
WEBSITE: HTTP://GERSLAB.UCONN.EDU

From: Naresh Palaiya
Sent: Tuesday, September 24, 2019 10:05 AM
To: GERSL/Fmask
Cc: Subscribed
Subject: [GERSL/Fmask] help required to automate fmask on mac (#11)

Hi,
I have download the 4.0 version of fmask and i was able to mask the clouds etc using the GUI. I wanted to understand how do i automate using command line. I have gone through the tutorials which was written for 3.3. version and for windows. But didn't understand.
Moreover, I have one more question what does " Number of dilated pixels for XYZ" means ? Does it mean you take 33 matrix and replace the whole 33 matrix with one value?

**Comment by qsly09** [comment]
Hi,

The Fmask 4.0 tool using the command line is the same as the 3.3. Please simply try to CD into your data folder, and then trigger the Fmask tool working. In addition, the dilation process is actually to make a buffer around the detected clouds and cloud shadows. The default buffer size is 3-pixels. If no special purposes, the default value should be good for you. Thank you.

Best,

GERSL

**Comment by palaiya** [comment]
@qsly09 I already tried what you said "CD" to the respective directory and use it in the same way. But the problem is like when i try to execute the fmask executable even after setting the `DYLD_LIBRARY_PATH` it throws the following exception as attached in the screenshot

<img width="1265" alt="Issue" src="https://user-images.githubusercontent.com/10070831/65542267-7e2dda00-df2c-11e9-976f-923adc4f9f5e.png">
