### ISSUE TITLE
Running FMask 4 on windows without GUI

### ISSUE THREAD

**Issue by andreas0806** [GERSL/Fmask4#12]
Hello,
I somehow have troubel to run fmask 4 on windows from the cmd-line without the GUI.
Running the exe FMask.exe from the cmd-line after I changed to the granule dir of a S2 scene always fires up the GUI. When I specify some additional parameter like "FMask.exe 3 3 0 20" I get a messagebox with the info "to many parameter" ?
What am I doing wrong

**Comment by qsly09** [comment]
Hi,
Please try to 'Fmask_4_0 3 3 0 20'. Thank you

Best,

**Comment by andreas0806** [comment]
Hi,
On linux I see the Fmask_4_0 application and also the parameter input on the cmd-line works, bun unfortunately on Windows I dont see a Fmask_4_0.exe anywhere on the installation. I only find a Fmask.exe in the subdirectory "application". 
Best,

**Comment by andreas0806** [comment]
Hi (again),
I found my problem, after I looked at your downloads at Google Drive a realized that the version without GUI is a different download. So after I installed this one everything works fine. Sorry for the confusion.
Best regards,
