### ISSUE TITLE
Fmask 4.1 errors with Landsat Collection 2 data.

### ISSUE THREAD

**Issue by sharkinsspatial** [GERSL/Fmask4#14]
We've begun some initial testing of Fmask with the new [Landsat Collection 2 data](https://www.usgs.gov/land-resources/nli/landsat/landsat-collection-2-level-1-data?qt-science_support_page_related_con=1#qt-science_support_page_related_con) in anticipation of its release later this year.  

There are some structural and metadata changes at the product level which are detailed [here](https://www.usgs.gov/media/files/landsat-collection-1-vs-collection-2-summary).  When running Fmask 4.1 with one of the Collection 2 [samples](https://landsat.usgs.gov/sites/default/files/C2_Sample_Data/LC08_L1TP_140041_20130503_20200330_02_T1.zip) we are receiving the following error.
```
Error using GRIDobj (line 295)
GRIDobj cannot read the TIF-file because it does not have a tfw-file.
Error in nd2toarbt (line 575)
Error in LoadData (line 101)
Error in autoFmask (line 114)
Error in Fmask_4_1 (line 10)
TopoToolbox:GRIDobj:read
```
Which indicates an error at the `geotiffread` [level](https://github.com/wschwanghart/topotoolbox/blob/master/%40GRIDobj/GRIDobj.m#L254=L302).  As a note, the `geotiffread` method is listed as not recommended in the official Matlab [documentation](https://www.mathworks.com/help/map/ref/geotiffread.html).

Unfortunately we do not have access to a Matlab installation to try and diagnose and debug these lower level read issues.

**Comment by qsly09** [comment]
We have noted this problem, and we will fix it soon. I will leave another message here once done. Thank you.

**Comment by qsly09** [comment]
Hi Sharkinsspatial,

The Fmask has been updated for processing the new Landsat Collection 2 data (Fmask 4.2). Please start it by 'Fmask_4_2' if you are using the standalone without GUI.

Thank you.

S.
