### ISSUE TITLE
Fmask4.2 for MacOS

### ISSUE THREAD

**Issue by LLeiSong** [GERSL/Fmask4#16]
Hi @qsly09 ,

Based on README, there should be an installer of Fmask 4.2 for Mac in the google drive. However, I didn't find any in the drive. Is there an update or something? 

Please help to check about this. Thanks a lot.

Best,
Lei

**Comment by j08lue** [comment]
There is always Docker, too, e.g. https://github.com/DHI-GRAS/fmaskilicious

**Comment by LLeiSong** [comment]
> There is always Docker, too, e.g. https://github.com/DHI-GRAS/fmaskilicious

 @j08lue You are absolutely right. Sometimes just being too lazy, which is bad. Thanks a lot for the hard work. The repo works like a charm with a bit changes for Fmask 4.2. BTW, love the name of the repo.

**Comment by j08lue** [comment]
> with a bit changes for Fmask 4.2

Good to know! Please consider opening a PR for your updates.
