### ISSUE TITLE
Error using ReadSunViewGeometryMSI - Fmask 4.3 on Linux, Sentinel-2

### ISSUE THREAD

**Issue by tomas4** [GERSL/Fmask4#17]
When trying the non-gui Fmask with Sentinel-2 data, following error is always showing up. It works fine with Landsat-7. Tried with two Sentinel-2 images, one recent, one 2016, downloaded from the ESA/Copernicus Scihub. Just changed directory to the subdirectory of GRANULE (S2A_MSIL1C_20201231T100411_N0209_R122_T33UWR_20201231T110732.SAFE/GRANULE/L1C_T33UWR_A028862_20201231T100414, per instructions in handbook) and ran the program without any parameters. Full console output including prompt showing folder location:

```
tom@uozp46:/media/Data/GISdata/DPZ/Chlorofyl-vzorkovani/2020-12-31_R122_S2A_ns/L1C/S2A_MSIL1C_20201231T100411_N0209_R122_T33UWR_20201231T110732.SAFE/GRANULE/L1C_T33UWR_A028862_20201231T100414$ /usr/local/GERS/Fmask_4_3/application/Fmask_4_3
Fmask 4.3 start ...
Cloud/cloud shadow/snow dilated by 3/3/0 pixels.
Cloud probability threshold of 20.00%.
Load or calculate TOA reflectances.
Error using ReadSunViewGeometryMSI (line 29)
The metadata was wrongly loaded. Please input Sentinel-2 TOA data.

Error in nd2toarbt_msi (line 44)

Error in LoadData (line 48)

Error in autoFmask (line 114)

Error in Fmask_4_3 (line 10)
```

**Comment by qsly09** [comment]
Dear tomas4,

It works well on this Sentinel-2 image on my side. Could you please double confirm your data (L1C)? Make sure that in the subfolder of the 'GRANULE', there are only one .XML file and three folders as below picture.

If you have any further questions, just send an email to us.

Thanks!
Best,

Shi

![image](https://user-images.githubusercontent.com/22184904/105936579-f2492800-6021-11eb-9306-2756dc3c0d79.png)

**Comment by tomas4** [comment]
I double checked. Listing of the directory (ls -l):

```
celkem 556K
drwxr-x--- 1 tom tom    0 pro 31 14:18 AUX_DATA
drwxr-x--- 1 tom tom 4,0K pro 31 14:18 IMG_DATA
-rw-r----- 1 tom tom 539K pro 31 14:18 MTD_TL.xml
drwxr-x--- 1 tom tom  12K pro 31 14:18 QI_DATA
```

It occured to me, that I have the data quite deep in directory structure, so I tried link it to my home and run it from there, but the result is the same. Tried another L1C image from 2017, again the same. Is it possible I am missing some library/module on my system, which is used with Sentinel, but not used with Landsat? But it should show up in the console output I suppose.. I am at loss as what it could be. 
Maybe, if you tried with the same image, is the MTD_TL.xml file size exactly the same as mine? Here in bytes:

```
$ du -b MTD_TL.xml
551732	MTD_TL.xml
```

**Comment by tomas4** [comment]
After a while I tried it again with the same product, this time moving the product to my home directory and the process finished successfully. I do not know yet, if the problem was with the deep directory structure or a library/dependency which fixed itself with a package upgrade, but it was evidently a problem on my PC. Closing the issue and thanks.
