### ISSUE TITLE
Fmask 4.3 failing on sample granules for new Sentinel 2 processing baseline 4.

### ISSUE THREAD

**Issue by sharkinsspatial** [GERSL/Fmask4#21]
In preparation for ESA's planned January 25 update of the Sentinel 2 [processing baseline](https://sentinels.copernicus.eu/web/sentinel/technical-guides/sentinel-2-msi/processing-baseline) to 4.0.0. We are testing our processing pipeline for Harmonized Landsat Sentinel against the [sample products](https://inthub.copernicus.eu/news/News00543) they have provided.

When attempting to process any of these Baseline 4 sample products with Fmask 4.3 we receive the following error
```
Error using xmlread
--
Java exception occurred:
org.xml.sax.SAXParseException; systemId: file:/var/scratch/d529375f-d9c1-495b-8bb2-ff85568178f6/S2B_MSIL1C_20211010T105859_N7990_R094_T30SVG_20211117T185835/S2B_MSIL1C_20211010T105859_N7990_R094_T30SVG_20211117T185835.SAFE/GRANULE/L1C_T30SVG_A024001_20211010T110917/QI_DATA/MSK_DETFOO_B04.jp2; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
at org.apache.xerces.impl.XMLDocumentScannerImpl$PrologDispatcher.dispatch(Unknown Source)
at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
Error in xml2struct (line 53)
Error in ReadSunViewGeometryMSI (line 159)
Error in nd2toarbt_msi (line 44)
Error in LoadData (line 48)
Error in autoFmask (line 114)
Error in Fmask_4_3 (line 10)
MATLAB:Java:GenericException
```

Given the time sensitivity of this upcoming baseline release (January 25, 2022), Fmask will no longer work with granules produced after that date, nor reprocessed granules in the archive.  @qsly09 Would it be possible for your team to review these Baseline 4 updates and release an updated version of Fmask which can accommodate them?  cc @junchangju.

**Comment by qsly09** [comment]
The Fmask tool has been updated to version 4.4 for supporting the new Sentinel-2 data. Many thanks.

**Comment by sharkinsspatial** [comment]
@qsly09 We have updated our test containers to use version 4.4.  While attempting to run our integration tests (no other changes have been made other than the update to 4.4 and 4.3 was running correctly) we are seeing the following error 
```
ERROR: ld.so: object '/usr/local/MATLAB/v96/bin/glnxa64/glibc-2.17_shim.so' from LD_PRELOAD cannot be preloaded: ignored.
/usr/local/MATLAB/application/Fmask_4_4: error while loading shared libraries: libmwlaunchermain.so: cannot open shared object file: No such file or directory
```
Has the build process for the installer changed somehow?  I also noted a significant change in the size of the installer as version 4.3 was 2.8GB while version 4.4 is only 2.1GB. 

Has the Matlab version changed with this release?  Currently we use 
```
/usr/local/MATLAB/application/run_Fmask_4_4.sh /usr/local/MATLAB/v96 >> fmask_out.txt
```
to execute this script.  If the Matlab version used to create the installer has changed this may be the cause of the issue.

**Comment by qsly09** [comment]
I agree with your thoughts on the issue. This time I compiled the Fmask 4.4 from **Matlab 2020a** on Linux, and I also found the size of the installer is lower than that compiled by early Matlab versions (this may be a new feature from the new Matlab version). Could you please try to figure out the Matlab version problem on your side? If problems still exist, please let me know, and we can try to create an installer from old MATLAB versions. Thanks.

**Comment by sharkinsspatial** [comment]
@qsly09 I just did some further tests with the container and it appears that the installer was created using a newer version of Matlab.  So updating our command to use the v910 runtime
```
/usr/local/MATLAB/application/run_Fmask_4_4.sh /usr/local/MATLAB/v910 >> fmask_out.txt
```
solved the issue for us.

Thank you again for the quick work on version v4.4 so close to the holidays to handle the baseline 4 updates.  We'll finish our testing review this week but this should allow us to continue producing HLS products after the upcoming change over.
