### ISSUE TITLE
Run Fmask4.6 failed.

### ISSUE THREAD

**Issue by zhumorui** [GERSL/Fmask4#30]
Hi! When I open this Fmask_4_6.exe file in windows, it shows the following errors, and the same in Linux.
Btw, Fmask_4_5 runs sucessfully on my computer.  
![image](https://user-images.githubusercontent.com/54446407/194644782-8c18c6a8-f3a5-4a17-b86a-515b59211541.png)

**Comment by zhaohaiyanggit** [comment]
I found that using Fmask_4_6 by commond line is ok.  
You can have a try!

**Comment by zhumorui** [comment]
How do you run it, could you please share an example, Thanks!

**Comment by sqwev** [comment]
you can see my blog
https://blog.csdn.net/sqwev/article/details/127334182

**Comment by zhumorui** [comment]
Thanks!
