### ISSUE TITLE
What causes this error: 

### ISSUE THREAD

**Issue by evan-blaisdell** [GERSL/Fmask4#5]
![image](https://user-images.githubusercontent.com/8387574/46620537-02583900-caf3-11e8-832d-c1ebe1b70f0a.png)

**Comment by qsly09** [comment]
Can you detail your data, such which sensor, which product (TOA or SR), location, and date if available? Thank you.

**Comment by dionhaefner** [comment]
This looks like a duplicate of #3 (same error message).

**Comment by evan-blaisdell** [comment]
Yes indeed. I hadn't noticed it was only happening on partial coverages, as issue #3 notes.
